name: Phase 1 - Hub VPC

on:
  workflow_dispatch:


    
    
  push:
     branches:
      - main

    


permissions:
  id-token: write
  contents: read

jobs:
  phase1-hub:
    name: Create Hub VPC
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: hub

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::647132523867:role/github-actions-terraform-role-v1
          aws-region: ap-south-1

      - name: Check AWS identity
        run: aws sts get-caller-identity

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform 

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve  